third_party_dir = "third-party"

# [platform.macos-aarch64]
# target = "aarch64-apple-darwin"

# [platform.linux-x86_64]
# target = "x86_64-unknown-linux-gnu"

# [platform.kernel-aarch64]
# target = "aarch64-unknown-none"
